on:
  workflow_dispatch:
    inputs:
      tag_version:
        description: 'Version à releaser (par 1.0.0)'
        required: true

permissions:
  contents: write

jobs:
  create-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.ref }} # branche sur laquelle on a déclenché la création du tag (branche de release)

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Create Tag
        run: |
          git config --global user.name "Aymen"
          git config --global user.email "aymen330d@hotmail.fr"
          mvn versions:set -DnewVersion=${{ github.event.inputs.tag_version }}  
          git add pom.xml
          git commit -m "tag created ==> ${{ github.event.inputs.tag_version }}"
          git tag ${{ github.event.inputs.tag_version }}
          git push origin ${{ github.ref }} # on pousse les modif sur la branche (changement de version)
          git push origin ${{ github.event.inputs.tag_version }} # on pousse le nouveau tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
